{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 246066,
          "sha512": "b49a8338e58c0eaca60b1bf3a5d6f92bd10d91cb72b3f9933c6bc7e36a1afd9790407faa5bdc1913ee2787977f22a6efb3faa745db54897d0dbd1507fa7bc2a9",
          "sha256": "bf1644bc8f04ff2e5e505982d9cd781906213e96a64d090748461d16b1ea167a",
          "sha1": "0556acdbd0d2300e9ec645469312df78ff34225c",
          "md5": "2ba81a52fa52db48ca7828a99b5fe502"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 246066,
          "sha512": "b49a8338e58c0eaca60b1bf3a5d6f92bd10d91cb72b3f9933c6bc7e36a1afd9790407faa5bdc1913ee2787977f22a6efb3faa745db54897d0dbd1507fa7bc2a9",
          "sha256": "bf1644bc8f04ff2e5e505982d9cd781906213e96a64d090748461d16b1ea167a",
          "sha1": "0556acdbd0d2300e9ec645469312df78ff34225c",
          "md5": "2ba81a52fa52db48ca7828a99b5fe502"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 70335,
          "sha512": "dfcd3e1a6b38002a442d29b4813c6bbb81c8b1d6c3f21d32f06416ab5a6664283be457ccff9a2330e1914baedbe1e2c8f3768e9a30f87ef39dc664d7fd71635b",
          "sha256": "4e55414abb6306577928eec443f76f3bd6d72ce53d932a5d09f1db58a5efb942",
          "sha1": "06adc9e870165f97f27a8d39584993cf01e240f0",
          "md5": "cb5571c090df84ef6cb9789e7df885fb"
        }
      ]
    }
  ]
}
