{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 245935,
          "sha512": "8c750189165f32d61446178b3d966dabf25dffac6411ea0cf3c6f1d73cb72629107baa808c5adc22c9a5f21f3d0138b562ea62a3af529712b41059f8f18321ac",
          "sha256": "ae40f0295481df11cc98e3139908b4aecf25cdb5b2c51eb0dfe79ddca15e33e8",
          "sha1": "f4f92bd79a94a14ee589d59cd21b873f0693404d",
          "md5": "0953ee687d31a8a2c9279d1e9caa2f86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "2.1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 245935,
          "sha512": "8c750189165f32d61446178b3d966dabf25dffac6411ea0cf3c6f1d73cb72629107baa808c5adc22c9a5f21f3d0138b562ea62a3af529712b41059f8f18321ac",
          "sha256": "ae40f0295481df11cc98e3139908b4aecf25cdb5b2c51eb0dfe79ddca15e33e8",
          "sha1": "f4f92bd79a94a14ee589d59cd21b873f0693404d",
          "md5": "0953ee687d31a8a2c9279d1e9caa2f86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 70308,
          "sha512": "9339ba67dfcbdc1e5612a933a1816b9c1015b6d3ea561421ea04019cb3fdf7e07e9a0b1f6884685426228e8f2c2e479eeafdc1c4166b45bab18672702e50264b",
          "sha256": "3d4297b973ab6013e6e20548e73704c8abec3073688d75ced95439afbdd1e792",
          "sha1": "03b9fec3d470248959d2df2a7f9980fe131526c7",
          "md5": "6147b0bff14568d40c651e4f2189010b"
        }
      ]
    }
  ]
}
